# Reporting/Analytics Service Config
server.port=8085
spring.application.name=reporting-analytics-service

# Other service URLs
student.service.url=http://localhost:8081
enrolment.service.url=http://localhost:8082
library.service.url=http://localhost:8084


reporting.timeout.connect=3000
reporting.timeout.read=3000